-- MySQL Script generated by MySQL Workbench
-- Tue Mar 11 20:48:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tcc` ;

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tcc` DEFAULT CHARACTER SET utf8 ;
USE `tcc` ;

-- -----------------------------------------------------
-- Table `tcc`.`Acesso_Pessoas_Dispositivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tcc`.`Acesso_Pessoas_Dispositivos` ;

CREATE TABLE IF NOT EXISTS `tcc`.`Acesso_Pessoas_Dispositivos` (
  `pessoa_id` INT NOT NULL,
  `dispositivo_id` INT NOT NULL,
  `fingerprint_capturada` TINYINT NOT NULL DEFAULT 0,
  `enabled` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`pessoa_id`, `dispositivo_id`),
  INDEX `fk_Pessoas_has_Dispositivos_Dispositivos1_idx` (`dispositivo_id` ASC) VISIBLE,
  INDEX `fk_Pessoas_has_Dispositivos_Pessoas1_idx` (`pessoa_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoas_has_Dispositivos_Pessoas1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `tcc`.`Pessoas` (`pessoa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoas_has_Dispositivos_Dispositivos1`
    FOREIGN KEY (`dispositivo_id`)
    REFERENCES `tcc`.`Dispositivos` (`dispositivo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`Auditoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tcc`.`Auditoria` ;

CREATE TABLE IF NOT EXISTS `tcc`.`Auditoria` (
  `auditoria_id` INT NOT NULL AUTO_INCREMENT,
  `auditoria_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `auditoria_evento` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`auditoria_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`Dispositivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tcc`.`Dispositivos` ;

CREATE TABLE IF NOT EXISTS `tcc`.`Dispositivos` (
  `dispositivo_id` INT NOT NULL AUTO_INCREMENT,
  `dispositivo_codigo` VARCHAR(20) NOT NULL,
  `dispositivo_nome` VARCHAR(45) NOT NULL,
  `dispositivo_local` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dispositivo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`Pessoas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tcc`.`Pessoas` ;

CREATE TABLE IF NOT EXISTS `tcc`.`Pessoas` (
  `pessoa_id` INT NOT NULL AUTO_INCREMENT,
  `pessoa_nome` VARCHAR(60) NOT NULL,
  `pessoa_cpf` VARCHAR(11) NOT NULL,
  `pessoa_telefone` VARCHAR(14) NOT NULL,
  `pessoa_nascimento` DATE NULL,
  `pessoa_funcao` VARCHAR(60) NULL,
  `pessoa_idcard` VARCHAR(64) NOT NULL,
  `pessoa_administrador` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`pessoa_id`))
ENGINE = InnoDB;

USE `tcc` ;

-- -----------------------------------------------------
-- Placeholder table for view `tcc`.`vw_acesso_pendentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`vw_acesso_pendentes` (`pessoa_idcard` INT, `pessoa_nome` INT, `pessoa_id` INT, `dispositivo_codigo` INT);

-- -----------------------------------------------------
-- Placeholder table for view `tcc`.`vw_pessoas_autorizadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`vw_pessoas_autorizadas` (`idcard` INT, `nome` INT, `id` INT, `dispositivo_codigo` INT);

-- -----------------------------------------------------
-- Placeholder table for view `tcc`.`vw_administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`vw_administradores` (`idcard` INT);

-- -----------------------------------------------------
-- View `tcc`.`vw_acesso_pendentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tcc`.`vw_acesso_pendentes`;
DROP VIEW IF EXISTS `tcc`.`vw_acesso_pendentes` ;
USE `tcc`;
CREATE  OR REPLACE VIEW vw_acesso_pendentes AS
SELECT 
    p.pessoa_idcard,
    p.pessoa_nome,
    apd.pessoa_id,
    d.dispositivo_codigo
FROM Acesso_Pessoas_Dispositivos apd
JOIN Pessoas p ON apd.pessoa_id = p.pessoa_id
JOIN Dispositivos d ON apd.dispositivo_id = d.dispositivo_id
WHERE apd.fingerprint_capturada = 0;

-- -----------------------------------------------------
-- View `tcc`.`vw_pessoas_autorizadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tcc`.`vw_pessoas_autorizadas`;
DROP VIEW IF EXISTS `tcc`.`vw_pessoas_autorizadas` ;
USE `tcc`;
CREATE  OR REPLACE VIEW vw_pessoas_autorizadas AS
SELECT 
    p.pessoa_idcard as idcard,
    p.pessoa_nome as nome,
    apd.pessoa_id as id,
    d.dispositivo_codigo
FROM Acesso_Pessoas_Dispositivos apd
JOIN Pessoas p ON apd.pessoa_id = p.pessoa_id
JOIN Dispositivos d ON apd.dispositivo_id = d.dispositivo_id
WHERE apd.fingerprint_capturada = 1 and apd.enabled = 1;

-- -----------------------------------------------------
-- View `tcc`.`vw_administradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tcc`.`vw_administradores`;
DROP VIEW IF EXISTS `tcc`.`vw_administradores` ;
USE `tcc`;
CREATE  OR REPLACE VIEW `vw_administradores` AS
select p.pessoa_idcard as idcard from Pessoas p
Where p.pessoa_administrador = 1;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
